In [1]:
import numpy as np
import pandas as pd

In [2]:
train_labels = pd.read_csv("/kaggle/input/image-matching-challenge-2024/train/train_labels.csv")
train_labels.head()

image_name                                    rotation_matrix  \
0     00.png  0.999017467386748;-0.01951432487219089;0.03979...   
1     01.png  0.999147719991382;-0.021624129414769648;0.0351...   
2     02.png  0.9992527616183833;-0.02402019259931326;0.0302...   
3     03.png  0.9993946226667176;-0.02356062921667625;0.0255...   
4     04.png  0.9995276708105233;-0.02256816267742356;0.0208...   

                                  translation_vector  \
0  -0.011700149127917355;0.018812528601332625;0.3...   
1  -0.011610785964818585;0.016710808069866724;0.3...   
2  -0.011589797430545654;0.014113680489915202;0.3...   
3  -0.011471598819000773;0.011325953000912126;0.3...   
4  -0.011389007765655301;0.008237801582322509;0.3...   

                                  calibration_matrix               dataset  \
0  5809.066058292364;0.0;2496.9582994472266;0.0;5...  transp_obj_glass_cup   
1  5809.066058292364;0.0;2496.9582994472266;0.0;5...  transp_obj_glass_cup   
2  5809.066058292364;0.0;2496.9582994472266;0.0;5...  transp_obj_glass_cup   
3  5809.066058292364;0.0;2496.9582994472266;0.0;5...  transp_obj_glass_cup   
4  5809.066058292364;0.0;2496.9582994472266;0.0;5...  transp_obj_glass_cup   

                  scene  
0  transp_obj_glass_cup  
1  transp_obj_glass_cup  
2  transp_obj_glass_cup  
3  transp_obj_glass_cup  
4  transp_obj_glass_cup

In [3]:
def str_to_arr(string: str, shape: tuple[int,int]):
    lst = string.split(';')
    array = []
    for s in lst:
        array.append(float(s))
    return np.array(array).reshape(shape)

In [4]:
for i, row in train_labels.iterrows():
    _, rotation_matrix, translation_vector, calibration_matrix, __, ___ = row
    rotation_matrix = str_to_arr(rotation_matrix,(3,3))
    translation_vector = str_to_arr(translation_vector,(3,1))
    calibration_matrix = str_to_arr(calibration_matrix,(3,3))
    camera_matrix = np.dot(calibration_matrix, np.hstack((rotation_matrix, translation_vector)))
    print(camera_matrix)

[[ 5.86857478e+03  2.34513758e+03 -2.00521813e+02  9.13140149e+02]
 [ 2.52977063e+02  6.86655937e+02 -6.01471060e+03  7.86087488e+02]
 [ 2.61183058e-02  9.84596971e-01 -1.72877526e-01  3.92920895e-01]]
[[ 5.85846959e+03  2.37073333e+03  1.94953092e+02  9.07451598e+02]
 [ 2.41225557e+02  1.69602490e+03 -5.81184542e+03  7.69596174e+02]
 [ 2.17682798e-02  9.99756114e-01 -3.72216415e-03  3.90434803e-01]]
[[ 5.85055612e+03  2.31839652e+03  6.13253509e+02  9.02338243e+02]
 [ 2.29211587e+02  2.70905566e+03 -5.41486074e+03  7.50897798e+02]
 [ 1.83546596e-02  9.84370227e-01  1.75152401e-01  3.88338140e-01]]
[[ 5.83921654e+03  2.21172754e+03  9.95922055e+02  8.98771088e+02]
 [ 2.09531099e+02  3.58796604e+03 -4.87799485e+03  7.31769290e+02]
 [ 1.34832666e-02  9.40581505e-01  3.39300212e-01  3.86634556e-01]]
[[ 5.82924880e+03  2.03391042e+03  1.36496011e+03  8.96322323e+02]
 [ 1.86183722e+02  4.38464172e+03 -4.17761774e+03  7.11809797e+02]
 [ 9.18178286e-03  8.67059079e-01  4.98120716e-01  3.85461